version: '3'

services:
  doorman:
    build: doorman/.
    environment:
      - API_PORT=${DOORMAN_PORT}
      - LIB1=http://librarian1:${LIBRARIAN1_PORT}/api
      - LIB2=http://librarian2:${LIBRARIAN2_PORT}/api
      - LIB3=http://librarian3:${LIBRARIAN3_PORT}/api
    ports:
      - ${DOORMAN_PORT}:${DOORMAN_PORT}
    links:
      - librarian1
      - librarian2
      - librarian3
  librarian1:
    build: librarian/.
    environment:
      - API_PORT=${LIBRARIAN1_PORT}
    ports:
      - ${LIBRARIAN1_PORT}:${LIBRARIAN1_PORT}
  librarian2:
    build: librarian/.
    environment:
      - API_PORT=${LIBRARIAN2_PORT}
    ports:
      - ${LIBRARIAN2_PORT}:${LIBRARIAN2_PORT}
  librarian3:
    build: librarian/.
    environment:
      - API_PORT=${LIBRARIAN3_PORT}
    ports:
      - ${LIBRARIAN3_PORT}:${LIBRARIAN3_PORT}